# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculadora.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Calculadora(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(444, 515)
        Form.setMinimumSize(QtCore.QSize(444, 515))
        Form.setMaximumSize(QtCore.QSize(444, 515))
        Form.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.frame.setStyleSheet("background-color: white;")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.frame_2.setFont(font)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setHorizontalSpacing(0)
        self.gridLayout_3.setVerticalSpacing(5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit.setStyleSheet("border-radius: 5px;\n"
"border: 1px solid rgb(220, 220, 220);")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_3.addWidget(self.lineEdit, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_2, 0, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.btnC = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnC.sizePolicy().hasHeightForWidth())
        self.btnC.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        self.btnC.setFont(font)
        self.btnC.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnC.setStyleSheet("QPushButton{    \n"
"    border-radius: 10px;\n"
"    border: 2px solid lightgray;}\n"
"QPushButton:hover {\n"
"    background-color: lightgray;}")
        self.btnC.setObjectName("btnC")
        self.gridLayout_4.addWidget(self.btnC, 0, 0, 1, 1)
        self.btnPA = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPA.sizePolicy().hasHeightForWidth())
        self.btnPA.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnPA.setFont(font)
        self.btnPA.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnPA.setStyleSheet("QPushButton{    \n"
"    border-radius: 10px;\n"
"    border: 2px solid lightgray;}\n"
"QPushButton:hover {\n"
"    background-color: lightgray;}")
        self.btnPA.setObjectName("btnPA")
        self.gridLayout_4.addWidget(self.btnPA, 0, 1, 1, 1)
        self.btnMultiplicar = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMultiplicar.sizePolicy().hasHeightForWidth())
        self.btnMultiplicar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnMultiplicar.setFont(font)
        self.btnMultiplicar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnMultiplicar.setStyleSheet("QPushButton{    \n"
"    border-radius: 10px;\n"
"    border: 2px solid lightgray;}\n"
"QPushButton:hover {\n"
"    background-color: lightgray;}")
        self.btnMultiplicar.setObjectName("btnMultiplicar")
        self.gridLayout_4.addWidget(self.btnMultiplicar, 0, 3, 1, 1)
        self.btn7 = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn7.sizePolicy().hasHeightForWidth())
        self.btn7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn7.setFont(font)
        self.btn7.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn7.setStyleSheet("QPushButton{    \n"
"    border-radius: 10px;\n"
"    border: 2px solid lightgray;}\n"
"QPushButton:hover {\n"
"    background-color: lightgray;}")
        self.btn7.setObjectName("btn7")
        self.gridLayout_4.addWidget(self.btn7, 1, 0, 1, 1)
        self.btn4 = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn4.sizePolicy().hasHeightForWidth())
        self.btn4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn4.setFont(font)
        self.btn4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn4.setStyleSheet("QPushButton{    \n"
"    border-radius: 10px;\n"
"    border: 2px solid lightgray;}\n"
"QPushButton:hover {\n"
"    background-color: lightgray;}\n"
"")
        self.btn4.setObjectName("btn4")
        self.gridLayout_4.addWidget(self.btn4, 2, 0, 1, 1)
        self.btnPC = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPC.sizePolicy().hasHeightForWidth())
        self.btnPC.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnPC.setFont(font)
        self.btnPC.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnPC.setStyleSheet("QPushButton{    \n"
"    border-radius: 10px;\n"
"    border: 2px solid lightgray;}\n"
"QPushButton:hover {\n"
"    background-color: lightgray;}")
        self.btnPC.setObjectName("btnPC")
        self.gridLayout_4.addWidget(self.btnPC, 0, 2, 1, 1)
        self.btnDividir = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDividir.sizePolicy().hasHeightForWidth())
        self.btnDividir.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnDividir.setFont(font)
        self.btnDividir.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnDividir.setStyleSheet("QPushButton{    \n"
"    border-radius: 10px;\n"
"    border: 2px solid lightgray;}\n"
"QPushButton:hover {\n"
"    background-color: lightgray;}")
        self.btnDividir.setObjectName("btnDividir")
        self.gridLayout_4.addWidget(self.btnDividir, 1, 3, 1, 1)
        self.btnPunto = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPunto.sizePolicy().hasHeightForWidth())
        self.btnPunto.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnPunto.setFont(font)
        self.btnPunto.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnPunto.setStyleSheet("QPushButton{    \n"
"    border-radius: 10px;\n"
"    border: 2px solid lightgray;}\n"
"QPushButton:hover {\n"
"    background-color: lightgray;}")
        self.btnPunto.setObjectName("btnPunto")
        self.gridLayout_4.addWidget(self.btnPunto, 4, 0, 1, 1)
        self.btn8 = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn8.sizePolicy().hasHeightForWidth())
        self.btn8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        self.btn8.setFont(font)
        self.btn8.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn8.setStyleSheet("QPushButton{    \n"
"    border-radius: 10px;\n"
"    border: 2px solid lightgray;}\n"
"QPushButton:hover {\n"
"    background-color: lightgray;}")
        self.btn8.setObjectName("btn8")
        self.gridLayout_4.addWidget(self.btn8, 1, 1, 1, 1)
        self.btn1 = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn1.sizePolicy().hasHeightForWidth())
        self.btn1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn1.setFont(font)
        self.btn1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn1.setStyleSheet("QPushButton{    \n"
"    border-radius: 10px;\n"
"    border: 2px solid lightgray;}\n"
"QPushButton:hover {\n"
"    background-color: lightgray;}")
        self.btn1.setObjectName("btn1")
        self.gridLayout_4.addWidget(self.btn1, 3, 0, 1, 1)
        self.btn9 = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn9.sizePolicy().hasHeightForWidth())
        self.btn9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn9.setFont(font)
        self.btn9.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn9.setStyleSheet("QPushButton{    \n"
"    border-radius: 10px;\n"
"    border: 2px solid lightgray;}\n"
"QPushButton:hover {\n"
"    background-color: lightgray;}")
        self.btn9.setObjectName("btn9")
        self.gridLayout_4.addWidget(self.btn9, 1, 2, 1, 1)
        self.btn6 = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn6.sizePolicy().hasHeightForWidth())
        self.btn6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn6.setFont(font)
        self.btn6.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn6.setStyleSheet("QPushButton{    \n"
"    border-radius: 10px;\n"
"    border: 2px solid lightgray;}\n"
"QPushButton:hover {\n"
"    background-color: lightgray;}")
        self.btn6.setObjectName("btn6")
        self.gridLayout_4.addWidget(self.btn6, 2, 2, 1, 1)
        self.btnSuma = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSuma.sizePolicy().hasHeightForWidth())
        self.btnSuma.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnSuma.setFont(font)
        self.btnSuma.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnSuma.setStyleSheet("QPushButton{    \n"
"    border-radius: 10px;\n"
"    border: 2px solid lightgray;}\n"
"QPushButton:hover {\n"
"    background-color: lightgray;}")
        self.btnSuma.setObjectName("btnSuma")
        self.gridLayout_4.addWidget(self.btnSuma, 3, 3, 1, 1)
        self.btnRestar = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnRestar.sizePolicy().hasHeightForWidth())
        self.btnRestar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnRestar.setFont(font)
        self.btnRestar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnRestar.setStyleSheet("QPushButton{    \n"
"    border-radius: 10px;\n"
"    border: 2px solid lightgray;}\n"
"QPushButton:hover {\n"
"    background-color: lightgray;}")
        self.btnRestar.setObjectName("btnRestar")
        self.gridLayout_4.addWidget(self.btnRestar, 2, 3, 1, 1)
        self.btn5 = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn5.sizePolicy().hasHeightForWidth())
        self.btn5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn5.setFont(font)
        self.btn5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn5.setStyleSheet("QPushButton{    \n"
"    border-radius: 10px;\n"
"    border: 2px solid lightgray;}\n"
"QPushButton:hover {\n"
"    background-color: lightgray;}")
        self.btn5.setObjectName("btn5")
        self.gridLayout_4.addWidget(self.btn5, 2, 1, 1, 1)
        self.btn2 = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn2.sizePolicy().hasHeightForWidth())
        self.btn2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn2.setFont(font)
        self.btn2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn2.setStyleSheet("QPushButton{    \n"
"    border-radius: 10px;\n"
"    border: 2px solid lightgray;}\n"
"QPushButton:hover {\n"
"    background-color: lightgray;}")
        self.btn2.setObjectName("btn2")
        self.gridLayout_4.addWidget(self.btn2, 3, 1, 1, 1)
        self.btn3 = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn3.sizePolicy().hasHeightForWidth())
        self.btn3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn3.setFont(font)
        self.btn3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn3.setStyleSheet("QPushButton{    \n"
"    border-radius: 10px;\n"
"    border: 2px solid lightgray;}\n"
"QPushButton:hover {\n"
"    background-color: lightgray;}")
        self.btn3.setObjectName("btn3")
        self.gridLayout_4.addWidget(self.btn3, 3, 2, 1, 1)
        self.btn0 = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn0.sizePolicy().hasHeightForWidth())
        self.btn0.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn0.setFont(font)
        self.btn0.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btn0.setStyleSheet("QPushButton{    \n"
"    border-radius: 10px;\n"
"    border: 2px solid lightgray;}\n"
"QPushButton:hover {\n"
"    background-color: lightgray;}")
        self.btn0.setObjectName("btn0")
        self.gridLayout_4.addWidget(self.btn0, 4, 1, 1, 1)
        self.btnIgual = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnIgual.sizePolicy().hasHeightForWidth())
        self.btnIgual.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnIgual.setFont(font)
        self.btnIgual.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnIgual.setStyleSheet("QPushButton{    \n"
"    border-radius: 10px;\n"
"    border: 2px solid lightgray;}\n"
"QPushButton:hover {\n"
"    background-color: lightgray;}")
        self.btnIgual.setObjectName("btnIgual")
        self.gridLayout_4.addWidget(self.btnIgual, 4, 2, 1, 2)
        self.gridLayout_2.addWidget(self.frame_3, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Calculadora Python"))
        self.label.setText(_translate("Form", "CalculadoraQT"))
        self.btnC.setText(_translate("Form", "C"))
        self.btnPA.setText(_translate("Form", "("))
        self.btnMultiplicar.setText(_translate("Form", "*"))
        self.btn7.setText(_translate("Form", "7"))
        self.btn4.setText(_translate("Form", "4"))
        self.btnPC.setText(_translate("Form", ")"))
        self.btnDividir.setText(_translate("Form", "/"))
        self.btnPunto.setText(_translate("Form", "."))
        self.btn8.setText(_translate("Form", "8"))
        self.btn1.setText(_translate("Form", "1"))
        self.btn9.setText(_translate("Form", "9"))
        self.btn6.setText(_translate("Form", "6"))
        self.btnSuma.setText(_translate("Form", "+"))
        self.btnRestar.setText(_translate("Form", "-"))
        self.btn5.setText(_translate("Form", "5"))
        self.btn2.setText(_translate("Form", "2"))
        self.btn3.setText(_translate("Form", "3"))
        self.btn0.setText(_translate("Form", "0"))
        self.btnIgual.setText(_translate("Form", "="))
